feat : Add putmapping and deletemapping in BoardController
jhkang1517/fhir-validator pull request #19
Opened 2022-06-30 05:34 UTC by Jayyouu

BoardController에 putmapping과 deletemapping 구현 했습니다.
Putmapping도 postmapping 처럼 유효성 검증이 필요한 것 같아 valid 어노테이션 이용하였습니다.
url도 class 단위로 baord라고 묶어주고 기능 메소드 별로 get/post/put/delete로 나눠봤습니다.
확인 부탁드립니다.

2022-06-30 06:21 UTC, jhkang1517 requested changes
리뷰 완료 했습니다. 

수정 사항 반영하셔서 재커밋 해주세요 ~

2022-06-30 06:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    @GetMapping("/get")
RESTful 한 표현을 위해서 `/get `보다는 GET 이라는 HTTP Method 로 표현을 하고, URL 매핑은 기존 `/board` 로 가는 것이 좋아보입니다. 

아래 문서 3.5 제목 내용 확인 부탁드립니다.
_https://server-engineer.tistory.com/886_

2022-06-30 06:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +
공백 제거 필요합니다.

2022-06-30 06:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    @PutMapping("/put")
위에 써드린 /get 과 동일한 내용입니다.

2022-06-30 06:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    }
DELETE 는 우선 특정 boardId 를 PathParameter 로 받아서 지우는 방식으로 개발하도록 하겠습니다. return 은 우선 입력받은 boardId 로 해주세요.

2022-06-30 06:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/dto/request/board/BoardRequest.java
> +    @NotEmpty
@NotNull , @NotBlank , @NotEmpty 사용법에 대해서 다시 살펴보시는게 좋을 것 같습니다.

이 부분은 정리해서 저에게 슬랙 메세지로 보내주세요.

2022-06-30 06:54 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardRequest brq(@Valid @RequestBody BoardRequest brq) {
변수 표기법 통일 하려니 위 postmapping 부분과 매개변수가 같아 오버로딩이 안되어 변수명을 변경했는데, 이럴때는 변수명을 어떻게 지정하면 되나요??

2022-06-30 08:30 UTC, Jayyouu commented
리뷰 하신부분 수정해서 다시 커밋 했습니다.
확인 부탁드립니다

2022-06-30 14:51 UTC, jhkang1517 requested changes
완성도가 점점 높아지고 있습니다~ 조금만 더 보완해주세요!

선임님이 만드신 api들을 보면 `/board` 를 동일하게 사용하고 있는 패턴을 확인 하실 수 있으실 거에요.

중복을 줄여나가는 것도 좋은 코드를 만드는 방법 중 하나이니, `/board` 를 공통화하는 방법도 찾아보셔서 반영해주세요~

2022-06-30 14:51 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardResponse roadboard() {
* `road -> load`
* `roadboard` -> `road`**B**`oard`
수정 부탁드립니다~

2022-06-30 14:51 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardRequest deleteboard(@PathVariable Long boardId) {
`deleteboard` ->` delete`**B**`oard`

카멜 표기법을 준수하는 습관을 들입시다~

2022-06-30 14:51 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardRequest createboard(@Valid @RequestBody BoardRequest boardRequest) {
여기도 마찬가지로 카멜 표기법 준수해주세요~

2022-07-01 00:45 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardResponse roadboard() {
수정했습니다. 카멜표기법 준수하겠습니다

2022-07-01 00:45 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardRequest deleteboard(@PathVariable Long boardId) {
위와 동일하게 카멜표기법으로 수정했습니다.

2022-07-01 00:46 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardRequest createboard(@Valid @RequestBody BoardRequest boardRequest) {
위와 동일하게 카멜표기법으로 수정했습니다.

2022-07-01 00:47 UTC, Jayyouu commented
리뷰해주신 부분 수정했습니다.
/board를 공통화 하기 위해 클래스에 @RequestMapping 이용하여 /board 로 묶어봤습니다.

2022-07-01 01:10 UTC, jhkang1517 requested changes

2022-07-01 01:10 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardResponse loadBoard() {
load 는 개발에서는 보통 "적재" 혹은 "파일을 올리다" 정도의 느낌으로 사용됩니다.
그래서 파일을 내려받는 행위를 download 라고 부릅니다.

load의 현재진행형인 loading (로딩) 이 있지만, 이 또한 '불러오는 중' 이나 '읽는 중' 정도로 해석이 되기 때문에 저희가 가진 기능을 가장 직관적으로 나타내는 것은 아닌 단어라고 생각합니다. 저희는 진행 중인 상태가 아니라 실제로 값을 불러와서 그 값을 리턴하니까요.

이러한 메소드명을 짓는 규칙을 명명규칙(Naming Rule) 이라고 합니다.
지금은 메소드명이 크게 문제가 되지 않지만, 앞서 말씀드렸듯 향후 확장성과 일관성을 고려한다면 초기부터 이러한 메소드 하나를 짓는데에도 신경을 써야합니다.

제가 알고있는 일반적으로 사용하는 명명규칙은 아래와 같은 것들이 있습니다.
POST(생성) -> insertXXX , addXXX
GET(읽기) -> selectXXX , getXXX
PUT(수정) -> updateXXX , editXXX
DELETE(삭제) -> deleteXXX , removeXXX
GET(여러건) -> selectXXXList , selectXXXs, getXXXList , getXXXs 

명명규칙에 대해 더 알아보신 다음에, 선임님이 적절하다고 판단되는 명명규칙을 선택하신 후, 나머지 메소드명들을 명명규칙에 맞게 통일시켜주세요.

2022-07-01 01:58 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public BoardResponse loadBoard() {
리뷰 하신부분 수정했습니다.
[https://dexcore.tistory.com/838](url) 참조하여 수정하였습니다.

2022-07-01 02:06 UTC, jhkang1517 approved these changes

2022-07-01 02:06 UTC, merged