Feat/12/test board controller
jhkang1517/fhir-validator pull request #22
Opened 2022-07-04 08:14 UTC by Jayyouu

test에 BoardControllerTest 클래스 생성후 get, post, put mapping에 관한 테스트 추가했습니다.

2022-07-04 08:43 UTC, jhkang1517 requested changes
BoardRequest.builder()
                    .boardId(3L)
                    .title("aaaa")
                    .contents("bbbb")
                    .writer("cccc")
                    .build();
현재 BoardRequeset 를 build 하는 코드 중복이 발생하고 있습니다.
중복을 제거해보는 연습을 해보시면 좋을 것 같습니다. 이 부분도 반영 부탁드려요.

2022-07-04 08:43 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +
테스트를 위해 만든 불필요한 api는 삭제해주세요~ ✂️

2022-07-04 08:43 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +@WebMvcTest(BoardController.class)
@WebMvcTest(BoardController.class) 여기서 (BoardController.class) 는 왜 사용하신 건가요? 🙋‍♂️

2022-07-04 08:43 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +    }
마찬가지로 불필요한 api 는 삭제해주세요! ✂️

2022-07-04 08:43 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +                                .content(objectMapper.writeValueAsString(boardRequest))
get, put 도 마찬가지로 적용해주세요~

2022-07-04 09:01 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +
네 삭제했습니다

2022-07-04 09:04 UTC, Jayyouu commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +@WebMvcTest(BoardController.class)
`@WebMvcTest`에 ()안에 매개변수를 넣으면 ()안에 작성된 클래스만 실제로 로드하여 테스트를 진행하고, 넣지 안으면 컨트롤러와 연관된 Bean이 모두 로드된다고 해서 간단히 BoardController.class만 테스트 하기 위해 넣었습니다. 불필요하면 제거하겠습니다.

2022-07-04 09:04 UTC, Jayyouu commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +    }
네 삭제했습니다.

2022-07-04 09:05 UTC, Jayyouu commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +                                .content(objectMapper.writeValueAsString(boardRequest))
import에 추가하여 메서드에서 명시하지 않고 반영했습니다.

2022-07-04 09:06 UTC, Jayyouu commented
BoardRequeset 를 build 하는 코드 중복을 피하기 위해 class단에 build하는 코드를 사용해서 중복을 제거해봤습니다.

2022-07-05 00:08 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +@WebMvcTest(BoardController.class)
음 그렇다면 넣는 것이 적절해 보입니다. 그대로 남겨놔도 괜찮을 것 같습니다.

2022-07-05 00:41 UTC, jhkang1517 requested changes

2022-07-05 00:41 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +    @DisplayName("getMappingTest")
`@DisplayName`은 A개발자가 작성한 테스트코드를 다른 사람이 이해할 수 있도록 풀어서 설명해주면 좋습니다.
`@DisplayName` 말고도 Test Method 자체를 길게 늘여쓰는 방법도 있는데, 우선 저희는 `@DisplayName` 어노테이션을 사용하도록 하겠습니다.

우선 저희는 gradle 기반이기 때문에 IntelliJ 설정이 필요합니다.
_https://effortguy.tistory.com/114_ 위 링크 참조하셔서 설정해주세요.

그 다음 Given , When , Then 공식에 따라 DisplayName 을 작성해주세요. 
길이 제한 없으며, 무엇이 주어졌을 때(Given), 무엇이 수행되고(When), 이에 따른 결과는 ~가 예상된다(Then) 식으로 작성해주시면 됩니다.

참고 자료는 아래 두 개 입니다.
_https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea_ 
_https://www.agilealliance.org/glossary/gwt/#q=~(infinite~false~filters~(postType~(~'page~'post~'aa_book~'aa_event_session~'aa_experience_report~'aa_glossary~'aa_research_paper~'aa_video)~tags~(~'given*20when*20then))~searchTerm~'~sort~false~sortDirection~'asc~page~1)_

2022-07-05 04:59 UTC, Jayyouu commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +    @DisplayName("getMappingTest")
`@DisplayName` 어노테이션을 사용해서 Given, When, Then 작성 했습니다.

2022-07-05 05:13 UTC, jhkang1517 approved these changes

2022-07-05 05:14 UTC, merged