feat : Add BoardRepository and Board document
jhkang1517/fhir-validator pull request #23
Opened 2022-07-07 01:00 UTC by Jayyouu

Board collection과 BoardRepository 작성하였고, BoardService는 class만 생성 해 놓은 상태입니다.
ID 타입은 String으로 선언하라 하셔서 Long 대신 String 타입 이용했습니다.

2022-07-11 01:21 UTC, jhkang1517 requested changes

2022-07-11 01:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public List<BoardResponse> getBoard() {
현재 List(다(多) 건) 조회를 하고 있습니다. 단 건 조회와 다 건 조회 두 개의 메소드로 나눠주시고, 적절한 메소드 명을 지어주세요.

2022-07-11 01:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +        }
List<BoardResponse> boardResponsesList = new ArrayList<>();
            for (Board board : boardList) {
                BoardResponse boardResponse = BoardResponse.from(board);
                boardResponsesList.add(boardResponse);
            }

Controller 영역에 적절한 로직은 아닌 것으로 보여집니다. BoardResponse.from() 이 있듯이, BoardResponse.fromList() 메소드를 만들어서 적절한 영역으로 옮겨주세요.

2022-07-11 01:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/dto/request/board/BoardRequest.java
> +    public static Board form(BoardRequest boardRequest) {
`form -> from` 변경해 주세요

2022-07-11 01:21 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/service/board/BoardService.java
> +        Board board = BoardRequest.form(boardRequest);
`form -> from`

2022-07-14 06:09 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/rest/controller/api/board/BoardControllerTest.java
> +
temp comment

2022-07-14 06:10 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +    public List<BoardResponse> getBoard() {
getBoard(단건) 와 getBoardList(다건) 두 개의 메소드로 나눠서 했습니다.

2022-07-14 06:10 UTC, jhkang1517 commented on src/test/java/com/espinas/fhir/config/MongoTestConfig.java
> +//}
추후 삭제 필요

2022-07-14 06:11 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/board/BoardController.java
> +        }
BoardResponse DTO로 메소드를 만들어 옮겼습니다.

2022-07-14 06:11 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/dto/request/board/BoardRequest.java
> +    public static Board form(BoardRequest boardRequest) {
수정했습니다.

2022-07-14 06:12 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/service/board/BoardService.java
> +        Board board = BoardRequest.form(boardRequest);
수정했습니다.

2022-07-15 05:27 UTC, merged