feat : Add UserCRUD in project
jhkang1517/fhir-validator pull request #38
Opened 2022-07-15 05:50 UTC by Jayyouu

userCRUD 구성했습니다.

2022-07-15 06:32 UTC, jhkang1517 requested changes

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +    private String userGender;
user 를 접두사로 사용하신 이유가 있을까요?

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +@NoArgsConstructor
`@NoArgsConstructor` 에 대해서, 그리고 `@NoArgsConstructor` 를 왜 써야하는지 작성해주세요.

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +    private String userId;
앞으로 userId , boardId 와 같은 부분들은 -> id 로 통일하겠습니다.

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +    public void updateUser(UserRequest userRequest) {
마찬가지로 접미사로 User 를 붙이신 이유가 있을까요?

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/user/UserController.java
> +        ResponseEntity<Response> response = response("Delete Success");
Controller 코드 통일성을 위해 userService 가 String 을 반환하게 해주세요

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +@NoArgsConstructor
아래 Request, Response 모두 포함되는 개념입니다.

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/dto/request/user/UserRequest.java
> +    public static User from(UserRequest userRequest) {
유저로부터 들어온 요청이 데이터베이스에 적재할 데이터가 되었다.
유저로부터 들어온 요청을 데이터베이스에 적재할 데이터로 바꾸었다.

사용자로부터 들어온 요청 -> 데이터베이스 -> 사용자에게 반환할 데이터 
이 흐름을 생각해보면,

Requeest to Domain
Response from Domain

선임님 생각에서 위 해석 말고 다른 부분으로 해석하신 부분이 있나요?

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/dto/response/user/UserResponse.java
> +    private String userGender;
BaseEntity 를 상속받은 만큼, createDate 와 modifiedDate 도 사용자에게 보여질 수 있게 DTO를 수정해주세요.

2022-07-15 06:32 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/service/user/UserService.java
> +    public User addUser(UserRequest userRequest) {
UserResponse 로 반환하게 해주세요. DELETE 제외 3개 공통 작업 필요합니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +    private String userGender;
다른 특별한 이유는 없이 구분을 위해 습관적으로 사용했습니다. 앞으로 수정하겠습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +@NoArgsConstructor
빌더 패턴으로 생성자를 생성해서 기본생성자를 생성하지 않으면 컴파일시 에러가 발생할 수 있어 기본 생성자를 생성해줘야 하는데, 이를 생성하기 위해  기본 생성자를 생성해주는 `@NoArgsConstructor `어노테이션을 사용해야 합니다.

https://pinokio0702.tistory.com/176 참조했습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +    private String userId;
네 알겠습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +    public void updateUser(UserRequest userRequest) {
위 이유와 동일합니다. 앞으로 수정하겠습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/user/UserController.java
> +        ResponseEntity<Response> response = response("Delete Success");
네 수정했습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/dto/request/user/UserRequest.java
> +    public static User from(UserRequest userRequest) {
UserReqeust로 부터 User객체에 저장한다고 생각하여 from을 생각했습니다. 
책임님 리뷰하신 부분으로 수정하겠습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/dto/response/user/UserResponse.java
> +    private String userGender;
수정했습니다.

2022-07-18 00:41 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/service/user/UserService.java
> +    public User addUser(UserRequest userRequest) {
UserResponse 로 반환하도록 수정했습니다.

2022-07-18 00:42 UTC, Jayyouu commented
리뷰 해주신 부분으로 수정했습니다.

2022-07-18 02:26 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +@NoArgsConstructor
**컴파일시 에러가 발생할 수 있어** 라는 설명은 명확하지 않은 설명인 것 같습니다.
실제로 컴파일시 에러가 발생합니다. 가능성이 아니라 명확한 사실로 적어주셔야 합니다.

또한 접근 제한자에 대해서도 한번 검색해보시고, 다시 한번 알게된 사실에대해 작성해주세요.

2022-07-18 04:16 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/service/user/UserService.java
> +        UserResponse userResponse = UserResponse.from(user);
https://minkukjo.github.io/framework/2020/07/05/Spring-130/ 위 게시물 참고해주세요

2022-07-18 06:58 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/domain/user/collection/User.java
> +@NoArgsConstructor
PUBLIC - 모든 곳에서 접근 가능
PROTECTED - 같은 패키지 또는 자식 클래스에서 사용
MODULE - 같은 패키지내에서 접근 가능
PACKAGE - 같은 패키지안에서 접근 가능하며 MODULE 과 동일한 기능
PRIVATE - 내부 클래스에서만 사용할 수 있음
NONE - 기본값인 PUBLIC 과 동일
-> 생성자의 대해서 접근제한자를 지정할 수 있습니다. 기본 접근제한자는 public

-> protected 이용하여 기본 생성자를 외부 어디에서 쉽게 접근 할 수 없도록 하여 안전성을 높이도록 할 수 있음.

https://www.popit.kr/%EC%8B%A4%EB%AC%B4%EC%97%90%EC%84%9C-lombok-%EC%82%AC%EC%9A%A9%EB%B2%95/ 와 https://lovethefeel.tistory.com/m/71 를 참조했습니다.

2022-07-18 06:58 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/user/UserController.java
> +        return response;
수정했습니다.

2022-07-18 06:58 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/service/user/UserService.java
> +        UserResponse userResponse = UserResponse.from(user);
파라미터로 던진 객체를 userRepository.save(user) 하여 저장하고 이를 저장되었다 생각하고 user 객체로 받았습니다. 
-> 참고 게시물을 보고 저장할 객체`(UserRequest.to(userRequest))`가 아닌 저장된 객체`(userRepository.save(user))`를 반환해야 값이 객체의 상태에 반영된다는 것을 알고 `userRepository.save(user))`를 반환하도록 수정했습니다.

2022-07-18 06:58 UTC, Jayyouu commented
리뷰 해주신 내용으로 수정했습니다.

2022-07-19 01:11 UTC, jhkang1517 commented on src/main/java/com/espinas/fhir/rest/controller/api/user/UserController.java
> +        return response;
서비스도 반영해주세요

2022-07-19 01:13 UTC, jhkang1517 reviewed
서비스만 마저 수정해주세요

2022-07-19 01:32 UTC, Jayyouu commented on src/main/java/com/espinas/fhir/rest/controller/api/user/UserController.java
> +        return response;
서비스에 반영하여 수정했습니다.

2022-07-19 01:32 UTC, Jayyouu commented
리뷰해주신 내용 반영하여 수정했습니다.

2022-07-20 00:28 UTC, Jayyouu commented
createdDate 가 null 값으로 등록되던 문제를 BaseEntity에 Version 설정을 해주니 제대로 저장되어 출력되었습니다.
https://uchupura.tistory.com/241 참조했습니다.

2022-07-21 01:59 UTC, Jayyouu commented
// post
"createdDate": "2022-07-20T17:36:33.715872",
"modifiedDate": "2022-07-20T17:36:33.715872"
// get
"createdDate": "2022-07-20T17:36:33.715"
"modifiedDate": "2022-07-20T17:36:33.715"
post date 시간이랑 get date 시간에서 초 단위가 post일 때는 nanosecond 해상도로 저장했는데, get은 millisecond 해상도로 저장되어 있습니다. 
mongoDB server가 milliesecond 단위 만 저장할 수 있습니다.
https://www.mongodb.com/docs/mongoid/current/release-notes/mongoid-7.4/ 참조했습니다.

2022-07-21 05:59 UTC, merged